-- Create testimonials table
create table if not exists public.testimonials (
  id bigint generated by default as identity primary key,
  author_name text not null,
  role text,
  content text not null,
  rating integer default 5,
  project_id uuid references public.portfolio(id),
  image_url text,
  is_featured boolean default false,
  created_at timestamp with time zone default timezone('utc'::text, now())
);

-- Enable Row Level Security
alter table public.testimonials enable row level security;

-- Create policies
create policy "Public testimonials are viewable by everyone."
  on public.testimonials for select
  using (true);

create policy "Users can insert their own testimonials."
  on public.testimonials for insert
  with check (true); -- Allow public submissions if desired, or restrict to auth.uid()

create policy "Admins can update testimonials."
  on public.testimonials for update
  using (auth.role() = 'authenticated'); -- Simplified for demo, ideally check for admin role

create policy "Admins can delete testimonials."
  on public.testimonials for delete
  using (auth.role() = 'authenticated');

-- Create profiles table
create table if not exists public.profiles (
  id uuid references auth.users on delete cascade not null primary key,
  email text,
  full_name text,
  avatar_url text,
  role text default 'admin',
  updated_at timestamp with time zone,
  created_at timestamp with time zone default timezone('utc'::text, now())
);

-- Enable RLS
alter table public.profiles enable row level security;

-- Create policies
create policy "Public profiles are viewable by everyone."
  on public.profiles for select
  using (true);

create policy "Users can insert their own profile."
  on public.profiles for insert
  with check (auth.uid() = id);

create policy "Users can update own profile."
  on public.profiles for update
  using (auth.uid() = id);

-- Function to handle new user signup
create or replace function public.handle_new_user()
returns trigger as $$
begin
  insert into public.profiles (id, email, full_name, role)
  values (new.id, new.email, new.raw_user_meta_data->>'full_name', 'admin');
  return new;
end;
$$ language plpgsql security definer;

-- Trigger the function every time a user is created
create or replace trigger on_auth_user_created
  after insert on auth.users
  for each row execute procedure public.handle_new_user();

-- Add status and published_at to projects table
ALTER TABLE "projects" ADD COLUMN "status" text DEFAULT 'draft';
ALTER TABLE "projects" ADD COLUMN "published_at" timestamp with time zone;
