/**
 * ALCS Estimator Engine — Discovery Handoff Schema
 * 
 * Typed bridge between Discovery Engine output (UserSignals + Archetype)
 * and the Estimator's cost computation layer.
 * 
 * Based on PRD §2 — all budget figures from Indian construction data:
 * - CPWD Plinth Area Rates (Nov 2023): ~₹2250/sqft baseline
 * - JK Cement metro build costs: ₹2700–5000/sqft
 * - NoBrokerHood renovation: ₹1500–4000/sqft
 */

// ─── Scope Classification ────────────────────────────────────────────────────

export type ProjectScope = "renovation" | "new_build" | "reconfigure";
export type BudgetConflictLevel = "none" | "minor" | "moderate" | "critical";
export type NegotiationStrategy = "standard" | "hero_focus" | "material_swaps" | "phased_execution" | "explore_rebuild";
export type PropertyFitTier = "excellent" | "good" | "constrained" | "poor";

// ─── Discovery Handoff (from Discovery Engine) ───────────────────────────────

export interface DiscoveryHandoff {
  /** Anonymous session ID */
  userId: string;
  timestamp: string;
  
  /** Primary emotional goal decoded from Discovery */
  emotionalGoal: string;
  
  /** Archetype name (e.g. "The Warm Modernist") */
  archetype: string;
  
  /** Archetype confidence score 0–1 */
  archetypeConfidence: number;

  lifestyle: {
    familyType: "Nuclear" | "Joint" | "Couple" | "Single" | "Other";
    members: number;
    children: number;
    workFromHome: boolean;
    hostingFreq: "Rarely" | "Sometimes" | "Often" | "Always";
    cookingRole: "Daily Ritual" | "Occasional" | "Outsourced";
    petsPresent: boolean;
  };

  property: {
    type: "apartment" | "villa" | "independent_floor" | "office" | "turnkey";
    areaSqFt: number;
    floors: number;
    ageYears: number;
    scope: ProjectScope;
    city: string;
    cityTier: "metro" | "tier1" | "tier2";
  };

  priorities: {
    mustHave: string[];         // room names tagged Must-Have
    niceToHave: string[];       // room names tagged Nice-to-Have
    emotionalWeights: Record<string, number>; // 0–1 weight per priority
  };

  sensory: {
    lighting: "warm" | "cool" | "natural" | "dramatic";
    colors: string[];
    textures: string[];
    luxuryResolvedAs: "invest-in-materials" | "invest-in-space" | "invest-in-tech" | "balanced";
  };

  budget: number; // ₹ raw value

  confidence: {
    emotionalGoal: number; // 0–1
    budget: number;
    rooms: number;
    overall: number;
  };

  /** Contradictions detected by ALCS intelligence engine */
  contradictions: string[];

  /** Negotiation memory from ReinterpretationGate */
  acceptedCompromises: string[];
}

// ─── Estimator Request ───────────────────────────────────────────────────────

export interface EstimatorRequest {
  discovery: DiscoveryHandoff;
  /** Override mode if user changes scope in Estimator */
  scopeOverride?: ProjectScope;
}

// ─── Estimator Response ──────────────────────────────────────────────────────

export interface EstimatorResponse {
  /** INR total range */
  totalMin: number;
  totalMax: number;

  costBreakdown: {
    structure: number;        // civil/structural work
    interiors: number;        // finishes, furniture, joinery
    mechanical: number;       // plumbing, electrical, HVAC
    design: number;           // professional fees
    contingency: number;      // 10–15% buffer
  };

  /** Phasing plan (if phased strategy selected) */
  phases?: {
    phase: number;
    label: string;
    scopeItems: string[];
    estimatedCost: number;
    timeline: string;
  }[];

  strategy: NegotiationStrategy;
  
  /** Human-readable strategy summary */
  strategyRationale: string;

  /** Concrete negotiation options generated by the engine */
  negotiationOptions: NegotiationOption[];

  /** 0–100: how well property fits desired lifestyle */
  fitScore: number;
  fitTier: PropertyFitTier;
  fitNarrative: string;

  /** Budget gap analysis */
  budgetConflict: {
    level: BudgetConflictLevel;
    gapPercent: number;       // negative = under budget, positive = over
    gapAmount: number;        // ₹ difference
  };

  timestamp: string;
}

// ─── Negotiation Option ──────────────────────────────────────────────────────

export interface NegotiationOption {
  id: string;
  strategy: NegotiationStrategy;
  label: string;
  description: string;
  /** Estimated cost saving in ₹ */
  savingsAmount: number;
  savingsPct: number;
  /** What the user gives up */
  tradeoff: string;
  /** Which priority this most affects */
  affectedPriority: string;
  /** 1 = best satisfaction preservation, 5 = most sacrifice */
  satisfactionImpact: 1 | 2 | 3 | 4 | 5;
}

// ─── Builder: UserSignals → DiscoveryHandoff ─────────────────────────────────

import type { UserSignals } from "@/types/discovery";

export function buildDiscoveryHandoff(
  signals: UserSignals,
  archetypeName: string,
  archetypeConfidence = 0.8
): DiscoveryHandoff {
  const mustHave = signals.roomPriorities
    ? Object.entries(signals.roomPriorities).filter(([, v]) => v === "Must-Have").map(([k]) => k)
    : [];
  
  const niceToHave = signals.roomPriorities
    ? Object.entries(signals.roomPriorities).filter(([, v]) => v === "Nice-to-Have").map(([k]) => k)
    : [];

  const emotionalWeights: Record<string, number> = {};
  if (signals.roomEmotionalWeights) {
    Object.entries(signals.roomEmotionalWeights).forEach(([room, w]) => {
      emotionalWeights[room] = w.weight ?? 0.5;
    });
  }

  const conflictIntelligence = signals.consultationIntelligence;

  return {
    userId: `anon-${Date.now()}`,
    timestamp: new Date().toISOString(),
    emotionalGoal: signals.emotionalGoal || "Comfortable Living",
    archetype: archetypeName,
    archetypeConfidence,

    lifestyle: {
      familyType: (signals.familyStructure as DiscoveryHandoff["lifestyle"]["familyType"]) || "Nuclear",
      members: signals.householdSize || 2,
      children: signals.childCount || 0,
      workFromHome: signals.workFromHome === "Yes",
      hostingFreq: (signals.hostingFrequency as DiscoveryHandoff["lifestyle"]["hostingFreq"]) || "Sometimes",
      cookingRole: (signals.cookingRole as DiscoveryHandoff["lifestyle"]["cookingRole"]) || "Occasional",
      petsPresent: signals.hasPets || false,
    },

    property: {
      type: (signals.propertyType as DiscoveryHandoff["property"]["type"]) || "apartment",
      areaSqFt: signals.carpetArea || 1000,
      floors: 1,
      ageYears: signals.propertyAge || 0,
      scope: (signals.projectScope as ProjectScope) || "renovation",
      city: signals.city || "",
      cityTier: (signals.cityTier as "metro" | "tier1" | "tier2") || "tier1",
    },

    priorities: { mustHave, niceToHave, emotionalWeights },

    sensory: {
      lighting: (signals.lightingPreference as DiscoveryHandoff["sensory"]["lighting"]) || "warm",
      colors: signals.colorPalette || [],
      textures: signals.selectedAdjectives.slice(0, 3),
      luxuryResolvedAs: (signals.luxuryResolution as DiscoveryHandoff["sensory"]["luxuryResolvedAs"]) || "balanced",
    },

    budget: signals.budgetValue || 2000000,

    confidence: {
      emotionalGoal: conflictIntelligence?.confidence.score
        ? conflictIntelligence.confidence.score / 100
        : 0.75,
      budget: signals.budgetBracket ? 0.8 : 0.5,
      rooms: mustHave.length > 0 ? 0.9 : 0.6,
      overall: conflictIntelligence?.confidence.score
        ? conflictIntelligence.confidence.score / 100
        : 0.7,
    },

    contradictions: conflictIntelligence?.interpretationConflict.detected
      ? [conflictIntelligence.interpretationConflict.description || "Visual and intent signals diverge"]
      : [],

    acceptedCompromises: signals.acceptedCompromises || [],
  };
}
