import fs from 'fs/promises';
import path from 'path';
import { DesignGenome } from './types.js';

// Placeholder imports for individual analyzers
// import { analyzeColors } from './color-analyzer.js';
// import { analyzeSpacing } from './spacing-analyzer.js';
import { analyzeTypography } from './typography-analyzer.js';
// import { analyzeMotion } from './motion-analyzer.js';
import { analyzeLayouts } from './layout-analyzer.js';
import { analyzeComponents } from './component-analyzer.js';
import { analyzeMotion } from './motion-analyzer.js';
import { analyzeColors } from './color-analyzer.js';
// import { analyzeImagery } from './imagery-analyzer.js';
// import { analyzeEnvironments } from './environment-analyzer.js';

const GENOME_FILE = path.join(process.cwd(), 'DESIGN_GENOME.md');
const SUMMARY_FILE = path.join(process.cwd(), 'GENOME_SUMMARY.md');
const JSON_FILE = path.join(process.cwd(), 'genome.json');

/**
 * The Design Genome is immutable. It is always regenerated from scratch
 * based on the reality of the codebase.
 */
async function buildGenome() {
  console.log("🧬 Extracting Design Genome...");

  const typographyFindings = await analyzeTypography();
  const layoutFindings = await analyzeLayouts();

  const componentFindings = await analyzeComponents({ typography: typographyFindings, layouts: layoutFindings });
  const motionFindings = await analyzeMotion({ components: componentFindings });
  const colorFindings = await analyzeColors({ typography: typographyFindings, layouts: layoutFindings, components: componentFindings, motion: motionFindings });

  const genome: DesignGenome = {
    version: "1.0.0",
    timestamp: new Date().toISOString(),
    driftScore: 0, // Will be calculated by comparing to previous version
    complianceScore: 0, 
    families: {
      colors: colorFindings,
      spacing: [],
      typography: typographyFindings,
      motion: motionFindings,
      layouts: layoutFindings,
      components: componentFindings,
      rhythm: [],
      materials: [],
      environments: []
    }
  };

  await generateGenomeMarkdown(genome);
  await generateSummaryMarkdown(genome);
  await fs.writeFile(JSON_FILE, JSON.stringify(genome, null, 2), 'utf-8');

  console.log("✅ DESIGN_GENOME.md, GENOME_SUMMARY.md, and genome.json generated.");
}

async function generateGenomeMarkdown(genome: DesignGenome) {
  let totalFindings = 0;
  let high = 0;
  let medium = 0;
  let low = 0;
  let totalConfidence = 0;

  for (const family of Object.values(genome.families)) {
    for (const finding of family) {
      totalFindings++;
      totalConfidence += finding.confidence;
      if (finding.confidence > 90) high++;
      else if (finding.confidence >= 70) medium++;
      else low++;
    }
  }

  const overallConfidence = totalFindings > 0 ? Math.round(totalConfidence / totalFindings) : 0;

  const content = `<!-- 
⚠️ DO NOT EDIT THIS FILE BY HAND.
This file is the living architectural fingerprint of the product.
It is auto-generated by the Design Genome Extractor. 
-->
# Design Genome

**Overall Genome Confidence:** ${overallConfidence}%
**Compliance Score:** ${genome.complianceScore}%
**Design Drift:** ${genome.driftScore > 0 ? '+' : ''}${genome.driftScore}%

### Finding Statistics
- **Total Findings:** ${totalFindings}
- **High Confidence (>90%):** ${high}
- **Medium Confidence (70-90%):** ${medium}
- **Low Confidence (<70%):** ${low} (Requires Review)

## Canonical Families

### Typography & Rhythm
${genome.families.typography.map(f => `
#### Intent: ${f.intent}
- **Observation:** ${f.observation}
- **Verdict:** ${f.verdict} → \`${f.migrationTarget || 'none'}\`
- **Confidence:** ${f.confidence}%
- **Evidence:** ${f.evidence.occurrences} occurrences
`).join('')}

### Layouts & Composition
${genome.families.layouts.map(f => `
#### Intent: ${f.intent}
- **Observation:** ${f.observation}
- **Verdict:** ${f.verdict} → \`${f.migrationTarget || 'none'}\`
- **Confidence:** ${f.confidence}%
- **Evidence:** ${f.evidence.occurrences} occurrences
`).join('')}

### Components & Geometry
${genome.families.components.map(f => `
#### Intent: ${f.intent}
- **Observation:** ${f.observation}
- **Verdict:** ${f.verdict} → \`${f.migrationTarget || 'none'}\`
- **Confidence:** ${f.confidence}%
- **Evidence:** ${f.evidence.occurrences} occurrences
`).join('')}

### Motion & Interaction
${genome.families.motion.map(f => `
#### Intent: ${f.intent}
- **Observation:** ${f.observation}
- **Verdict:** ${f.verdict} → \`${f.migrationTarget || 'none'}\`
- **Confidence:** ${f.confidence}%
- **Evidence:** ${f.evidence.occurrences} occurrences
`).join('')}

### Colors & Materials
${genome.families.colors.map(f => `
#### Intent: ${f.intent}
- **Observation:** ${f.observation}
- **Verdict:** ${f.verdict} → \`${f.migrationTarget || 'none'}\`
- **Confidence:** ${f.confidence}%
- **Evidence:** ${f.evidence.occurrences} occurrences
`).join('')}

`;

  await fs.writeFile(GENOME_FILE, content, 'utf-8');
}

async function generateSummaryMarkdown(genome: DesignGenome) {
  const content = `# Design Genome Summary

**Compliance Score:** ${genome.complianceScore}%
**New Drift:** ${genome.driftScore > 0 ? '+' : ''}${genome.driftScore}%

## Canonical Families
- **Colors:** ${genome.families.colors.length} canonical intents
- **Typography:** ${genome.families.typography.length} canonical intents
- **Layouts:** ${genome.families.layouts.length} canonical intents
- **Components:** ${genome.families.components.length} canonical intents
- **Motion:** ${genome.families.motion.length} canonical intents
- **Materials:** ${genome.families.materials.length} canonical intents
- **Environments:** ${genome.families.environments.length} canonical intents
`;

  await fs.writeFile(SUMMARY_FILE, content, 'utf-8');
}

buildGenome().catch(console.error);
