import { useStudio } from '../context/StudioContext';
import { motion } from 'framer-motion';
import { formatINR } from '@/lib/utils';
import { MATERIALS as MATERIAL_DATA } from '@/components/calculators/MaterialEstimator/data';
import { Printer, TrendingUp, Zap, ShieldCheck, DollarSign } from 'lucide-react';

export const ReportView = () => {
    const {
        atmosphere,
        selectedMaterialId,
        timeHorizon,
        propertyValue,
        projectArea,
        setProjectArea,
        totalCost,
        totalValue
    } = useStudio();

    const selectedMaterial = MATERIAL_DATA.find(m => m.id === selectedMaterialId);
    const netProfit = totalValue - totalCost;
    const roi = totalCost > 0 ? (netProfit / totalCost) * 100 : 0;

    return (
        <div className="w-full h-full bg-[#0a0a0a] overflow-y-auto custom-scrollbar p-8 md:p-12 pb-32">

            <div className="max-w-5xl mx-auto space-y-12">

                {/* Header */}
                <div className="flex flex-col md:flex-row justify-between items-start md:items-center gap-6 border-b border-white/10 pb-8">
                    <div>
                        <div className="flex items-center gap-2 mb-2">
                            <div className="h-1 w-6 bg-emerald-500 rounded-full" />
                            <span className="text-xs font-bold uppercase tracking-widest text-white/60">Executive Summary</span>
                        </div>
                        <h1 className="text-3xl md:text-4xl font-serif text-white">Project Intelligence Report</h1>
                        <p className="text-white/40 mt-2 text-sm">Generated by Digital Intelligence Studio</p>
                    </div>
                </div>
                <div className="flex items-center gap-4">
                    <div className="flex items-center gap-2 bg-white/5 border border-white/10 rounded-lg px-3 py-2">
                        <span className="text-[10px] uppercase tracking-widest text-white/40">Area (sqft)</span>
                        <input
                            type="number"
                            value={projectArea}
                            onChange={(e) => setProjectArea(Number(e.target.value))}
                            className="w-16 bg-transparent text-white font-mono text-center focus:outline-none focus:ring-1 focus:ring-emerald-500/50 rounded"
                            aria-label="Project Area in square feet"
                            placeholder="650"
                        />
                    </div>
                    <button className="flex items-center gap-2 px-4 py-2 bg-white text-black text-xs font-bold uppercase tracking-widest rounded-lg hover:bg-white/90 transition-colors">
                        <Printer className="w-4 h-4" /> Export PDF
                    </button>
                </div>
            </div>

            {/* Financial Overview Cards */}
            <div className="grid grid-cols-1 md:grid-cols-3 gap-6">
                {/* Total Investment */}
                <div className="bg-white/5 border border-white/10 rounded-2xl p-6">
                    <div className="flex items-center gap-3 text-white/50 mb-4">
                        <DollarSign className="w-4 h-4" />
                        <span className="text-xs font-bold uppercase tracking-widest">Total Investment</span>
                    </div>
                    <div className="text-3xl font-mono text-white mb-1">{formatINR(totalCost)}</div>
                    <p className="text-xs text-white/30">Capital Expenditure + 5Y Lifecycle</p>
                </div>

                {/* Value Created */}
                <div className="bg-emerald-900/10 border border-emerald-500/20 rounded-2xl p-6 relative overflow-hidden">
                    <div className="absolute top-0 right-0 p-4 opacity-10">
                        <TrendingUp className="w-16 h-16 text-emerald-500" />
                    </div>
                    <div className="flex items-center gap-3 text-emerald-400 mb-4">
                        <TrendingUp className="w-4 h-4" />
                        <span className="text-xs font-bold uppercase tracking-widest">Value Created (Alpha)</span>
                    </div>
                    <div className="text-3xl font-serif text-white mb-1">+{formatINR(totalValue)}</div>
                    <p className="text-xs text-emerald-400/50">Market Outperformance</p>
                </div>

                {/* ROI */}
                <div className="bg-white/5 border border-white/10 rounded-2xl p-6">
                    <div className="flex items-center gap-3 text-white/50 mb-4">
                        <span className="text-xs font-bold uppercase tracking-widest">Return on Design</span>
                    </div>
                    <div className="text-3xl font-mono text-white mb-1">{roi.toFixed(1)}%</div>
                    <p className="text-xs text-white/30">Net ROI over {timeHorizon} Years</p>
                </div>
            </div>

            {/* Detailed Modules Grid */}
            <div className="grid grid-cols-1 md:grid-cols-2 gap-8">

                {/* Atmosphere Module */}
                <div className="space-y-6">
                    <h3 className="text-lg font-serif text-white/80 border-b border-white/5 pb-2">Atmosphere Orchestrator</h3>
                    <div className="grid grid-cols-2 gap-4">
                        <div className="p-4 bg-white/5 border border-white/5 rounded-xl">
                            <div className="text-[10px] text-white/40 uppercase tracking-widest mb-1">Light Quality</div>
                            <div className="text-lg text-white font-medium">{atmosphere.stats.fixtureCount} Fixtures</div>
                            <div className="text-xs text-white/50">{atmosphere.stats.lumens.toLocaleString()} Lumens</div>
                        </div>
                        <div className="p-4 bg-white/5 border border-white/5 rounded-xl">
                            <div className="text-[10px] text-white/40 uppercase tracking-widest mb-1 flex items-center gap-1">
                                <Zap className="w-3 h-3 text-amber-500" /> Energy
                            </div>
                            <div className="text-lg text-white font-medium">{formatINR(atmosphere.stats.costs.annualEnergy)}/yr</div>
                            <div className="text-xs text-white/50">{atmosphere.stats.wattage} Watts Total</div>
                        </div>
                    </div>
                </div>

                {/* Investment/Material Module */}
                <div className="space-y-6">
                    <h3 className="text-lg font-serif text-white/80 border-b border-white/5 pb-2">Tactile Investment</h3>
                    <div className="grid grid-cols-2 gap-4">
                        <div className="p-4 bg-white/5 border border-white/5 rounded-xl">
                            <div className="text-[10px] text-white/40 uppercase tracking-widest mb-1">Material Selection</div>
                            <div className="text-lg text-white font-medium truncate">{selectedMaterial?.name}</div>
                            <div className="text-xs text-white/50">{formatINR(selectedMaterial?.price || 0)} / sq.ft</div>
                        </div>
                        <div className="p-4 bg-white/5 border border-white/5 rounded-xl">
                            <div className="text-[10px] text-white/40 uppercase tracking-widest mb-1 flex items-center gap-1">
                                <ShieldCheck className="w-3 h-3 text-emerald-500" /> Durability Risk
                            </div>
                            <div className="text-lg text-white font-medium capitalize">{selectedMaterial?.risk.label}</div>
                            <div className="text-xs text-white/50">Maintenance Score</div>
                        </div>
                    </div>
                </div>

            </div>

            {/* Strategy Module Summary */}
            <div className="bg-gradient-to-r from-purple-900/20 to-black border border-purple-500/20 rounded-2xl p-8">
                <div className="flex flex-col md:flex-row gap-8 justify-between items-center">
                    <div className="space-y-2">
                        <div className="flex items-center gap-2 text-purple-400 mb-2">
                            <TrendingUp className="w-4 h-4" />
                            <span className="text-xs font-bold uppercase tracking-widest">Long Term Strategy</span>
                        </div>
                        <h3 className="text-2xl font-serif text-white">
                            {timeHorizon}-Year Strategic Horizon
                        </h3>
                        <p className="text-sm text-white/60 max-w-lg">
                            Based on a property value of {formatINR(propertyValue)}, your design interventions are projected to generate significant additional equity.
                        </p>
                    </div>
                    <div className="text-right">
                        <div className="text-xs text-white/40 uppercase tracking-widest mb-1">Projected Net Appreciation</div>
                        <div className="text-4xl font-mono text-emerald-400">
                            {formatINR(netProfit)}
                        </div>
                    </div>
                </div>
            </div>

        </div>
    );
};
