-- ═══════════════════════════════════════════════════════════
-- Migration: Add ALCS Recommendation and Evidence to leads
-- Phase 15: Recommendation Explainability
-- ═══════════════════════════════════════════════════════════

ALTER TABLE leads
  ADD COLUMN alcs_execution_path text,
  ADD COLUMN alcs_confidence numeric,
  ADD COLUMN alcs_reasoning text,
  ADD COLUMN alcs_evidence jsonb,
  ADD COLUMN alcs_primary_drivers jsonb;

COMMENT ON COLUMN leads.alcs_execution_path IS 'ALCS Engine recommended execution path.';
COMMENT ON COLUMN leads.alcs_confidence IS 'ALCS Engine confidence score 0-100 for the recommendation.';
COMMENT ON COLUMN leads.alcs_reasoning IS 'Narrative Because... explanation generated by ALCS.';
COMMENT ON COLUMN leads.alcs_evidence IS 'Ledger of evidence entries used to calculate the ALCS recommendation.';
COMMENT ON COLUMN leads.alcs_primary_drivers IS 'List of primary drivers for the ALCS recommendation.';
