-- ============================================================
-- Blog Analytics Schema
-- Adds engagement tracking tables for the blog system
-- ============================================================
-- 1. Add missing columns to blogs table if not present
DO $$ BEGIN IF NOT EXISTS (
    SELECT 1
    FROM information_schema.columns
    WHERE table_name = 'blogs'
        AND column_name = 'category'
) THEN
ALTER TABLE public.blogs
ADD COLUMN category text DEFAULT 'Interior Design';
END IF;
IF NOT EXISTS (
    SELECT 1
    FROM information_schema.columns
    WHERE table_name = 'blogs'
        AND column_name = 'tags'
) THEN
ALTER TABLE public.blogs
ADD COLUMN tags text [] DEFAULT '{}';
END IF;
IF NOT EXISTS (
    SELECT 1
    FROM information_schema.columns
    WHERE table_name = 'blogs'
        AND column_name = 'author'
) THEN
ALTER TABLE public.blogs
ADD COLUMN author text DEFAULT 'CrossAngle Team';
END IF;
IF NOT EXISTS (
    SELECT 1
    FROM information_schema.columns
    WHERE table_name = 'blogs'
        AND column_name = 'read_time_minutes'
) THEN
ALTER TABLE public.blogs
ADD COLUMN read_time_minutes integer DEFAULT 5;
END IF;
IF NOT EXISTS (
    SELECT 1
    FROM information_schema.columns
    WHERE table_name = 'blogs'
        AND column_name = 'views_count'
) THEN
ALTER TABLE public.blogs
ADD COLUMN views_count integer DEFAULT 0;
END IF;
IF NOT EXISTS (
    SELECT 1
    FROM information_schema.columns
    WHERE table_name = 'blogs'
        AND column_name = 'is_featured'
) THEN
ALTER TABLE public.blogs
ADD COLUMN is_featured boolean DEFAULT false;
END IF;
IF NOT EXISTS (
    SELECT 1
    FROM information_schema.columns
    WHERE table_name = 'blogs'
        AND column_name = 'meta_title'
) THEN
ALTER TABLE public.blogs
ADD COLUMN meta_title text;
END IF;
IF NOT EXISTS (
    SELECT 1
    FROM information_schema.columns
    WHERE table_name = 'blogs'
        AND column_name = 'meta_description'
) THEN
ALTER TABLE public.blogs
ADD COLUMN meta_description text;
END IF;
END $$;
-- 2. Article Analytics — aggregated metrics per article
CREATE TABLE IF NOT EXISTS public.article_analytics (
    id bigint generated by default as identity primary key,
    article_id text NOT NULL,
    views integer DEFAULT 0,
    unique_views integer DEFAULT 0,
    avg_read_time_seconds numeric DEFAULT 0,
    scroll_completion_rate numeric DEFAULT 0,
    shares integer DEFAULT 0,
    cta_clicks integer DEFAULT 0,
    newsletter_signups integer DEFAULT 0,
    updated_at timestamp with time zone DEFAULT now()
);
CREATE INDEX IF NOT EXISTS idx_article_analytics_article_id ON public.article_analytics(article_id);
-- 3. Blog User Events — raw event log
CREATE TABLE IF NOT EXISTS public.blog_user_events (
    id bigint generated by default as identity primary key,
    event_type text NOT NULL,
    -- article_view, scroll_depth, reading_time, cta_click, tag_click, newsletter_signup
    article_id text,
    session_id text,
    metadata jsonb DEFAULT '{}',
    -- flexible payload: { depth: 75, button: "consultation", tag: "luxury" }
    device text,
    referrer text,
    country text,
    created_at timestamp with time zone DEFAULT now()
);
CREATE INDEX IF NOT EXISTS idx_blog_events_type ON public.blog_user_events(event_type);
CREATE INDEX IF NOT EXISTS idx_blog_events_article ON public.blog_user_events(article_id);
CREATE INDEX IF NOT EXISTS idx_blog_events_created ON public.blog_user_events(created_at);
-- 4. Newsletter Subscribers
CREATE TABLE IF NOT EXISTS public.newsletter_subscribers (
    id bigint generated by default as identity primary key,
    email text NOT NULL UNIQUE,
    source text DEFAULT 'blog',
    article_id text,
    created_at timestamp with time zone DEFAULT now()
);
-- 5. RLS Policies
ALTER TABLE public.article_analytics ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.blog_user_events ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.newsletter_subscribers ENABLE ROW LEVEL SECURITY;
-- Public can insert events (anonymous tracking)
CREATE POLICY "Anyone can insert blog events" ON public.blog_user_events FOR
INSERT WITH CHECK (true);
-- Only authenticated users can read events (admin panel)
CREATE POLICY "Authenticated users can read blog events" ON public.blog_user_events FOR
SELECT USING (auth.role() = 'authenticated');
-- Article analytics: public read, admin write
CREATE POLICY "Public can read article analytics" ON public.article_analytics FOR
SELECT USING (true);
CREATE POLICY "Authenticated can manage article analytics" ON public.article_analytics FOR ALL USING (auth.role() = 'authenticated');
-- Newsletter: public insert, admin read
CREATE POLICY "Anyone can subscribe to newsletter" ON public.newsletter_subscribers FOR
INSERT WITH CHECK (true);
CREATE POLICY "Authenticated can read newsletter subscribers" ON public.newsletter_subscribers FOR
SELECT USING (auth.role() = 'authenticated');
-- 6. RPC to record a blog event (batched-friendly)
CREATE OR REPLACE FUNCTION public.record_blog_event(
        p_event_type text,
        p_article_id text DEFAULT NULL,
        p_session_id text DEFAULT NULL,
        p_metadata jsonb DEFAULT '{}',
        p_device text DEFAULT NULL,
        p_referrer text DEFAULT NULL
    ) RETURNS void LANGUAGE plpgsql SECURITY DEFINER AS $$ BEGIN
INSERT INTO public.blog_user_events (
        event_type,
        article_id,
        session_id,
        metadata,
        device,
        referrer
    )
VALUES (
        p_event_type,
        p_article_id,
        p_session_id,
        p_metadata,
        p_device,
        p_referrer
    );
-- Auto-increment views_count on blogs table for article_view events
IF p_event_type = 'article_view'
AND p_article_id IS NOT NULL THEN
UPDATE public.blogs
SET views_count = COALESCE(views_count, 0) + 1
WHERE id = p_article_id;
END IF;
END;
$$;